# -*- coding: utf-8 -*-
"""arclm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z4jvjfWlX0NE5n10IH2IQvBH5vi-4qRH
"""

import time
from collections import Counter

import torch

from arclm import (
    Config,
    Generator,
    build_model,
    build_trainer,
    create_checkpoint_callback,
    format_duration,
    prepare_data,
)

def create_config() -> Config:
    return Config(
        # ======================
        # Model architecture
        # ======================
        embed_dim=256,
        num_blocks=8,
        block_size=150,
        dropout=0.1,

        # ======================
        # Data
        # ======================
        data_path="/content/drive/MyDrive/Colab Notebooks/data/wikitext/wikitext-1.81M.txt",
        max_data_size=30_000_000,
        validation_split=0.2,

        # ======================
        # Tokenizer
        # ======================
        tokenizer_type="sentencepiece",
        max_vocab=12_000,
        tokenizer_path="/content/drive/MyDrive/Colab Notebooks/models/tokenizer.model",

        # ======================
        # Training
        # ======================
        batch_size=1024,
        num_epochs=15,
        learning_rate=3e-4,
        weight_decay=0.01,
        grad_clip=1.0,
        training_log_interval=10,
        checkpoint_batch_interval=2,

        # ======================
        # Regularization
        # ======================
        early_stopping_patience=2,
        early_stopping_min_delta=1e-4,
        restore_best_model=True,

        # ======================
        # System
        # ======================
        device="cuda" if torch.cuda.is_available() else "cpu",
        seed=42,

        # ======================
        # I/O
        # ======================
        model_path="/content/drive/MyDrive/Colab Notebooks/models/arclm.pth",
    )

def main():
    start = time.time()
    config = create_config()
    torch.manual_seed(config.seed)

    print("\nArcLM training")
    print(config)

    data = prepare_data(config)
    config.vocab_size = data.vocab_size


    try:
        data.tokenizer.save(config.tokenizer_path)
    except Exception as e:
        print(f"Warning: Failed to save tokenizer: {e}")

    print(f"\nData tokens: {len(data.tokens):,}")
    print(f"Train tokens: {len(data.train_tokens):,}")
    print(f"Validation tokens: {len(data.val_tokens):,}")
    print(f"Vocab size: {data.vocab_size:,}")
    print(f"Train batches: {len(data.train_loader):,}")
    if data.val_loader is not None:
        print(f"Validation batches: {len(data.val_loader):,}")

    decoded_sample = data.tokenizer.decode(data.train_encoded[:20])
    counter = Counter(data.tokenizer.decode(data.train_encoded))
    print(f"Decoded sample: {decoded_sample}")
    print(f"Top tokens: {counter.most_common(5)}")

    model = build_model(config, data.vocab_size)
    print(f"Parameters: {model.get_num_parameters():,}")

    input("Press Enter to start training... | press Ctrl+C to exit")

    trainer = build_trainer(model, config)
    trainer.train(
        data.train_loader,
        config.num_epochs,
        val_loader=data.val_loader,
        early_stopping_patience=config.early_stopping_patience,
        min_delta=config.early_stopping_min_delta,
        checkpoint_callback=create_checkpoint_callback(config, data.tokenizer, data.vocab_size),
    )

    trainer.save(
        config,
        vocab=data.tokenizer.vocab,
        stoi=data.tokenizer.stoi,
        itos=data.tokenizer.itos,
        tokenizer_metadata=data.tokenizer.to_checkpoint(),
    )

    generator = Generator(
        model=model,
        stoi=data.tokenizer.stoi,
        itos=data.tokenizer.itos,
        block_size=config.block_size,
        device=torch.device(config.device),
        tokenizer=data.tokenizer,
    )
    print("\nGenerated sample:")
    print(generator.generate_string("The game began development", max_new_tokens=30, top_p=0.9))

    print(f"\nSaved model: {config.model_path}")
    print(f"Total time: {format_duration(time.time() - start)}")

main()
